### ISSUE TITLE
Use "lineage" not "classIdentity" to find units

### ISSUE THREAD

**Issue by ThePants999** [ThePants999/Yellowscribe#13]
Currently we find units by looking for assets whose `classIdentity` is "Unit". But this only works if they're a Unit or a direct subclass - it breaks if they're a sub-subclass, like Titan. Use `lineage` instead and check that it _contains_ "Unit".

**Comment by TheGameKnave** [comment]
Addressed in https://github.com/ThePants999/Yellowscribe/pull/14
