### ISSUE TITLE
Wounds greater than 16 error

### ISSUE THREAD

**Issue by appoteres** [ThePants999/Yellowscribe#21]
https://github.com/ThePants999/Yellowscribe/blob/af80deece46eb0a824d911c9d778d75f61aa99e9/lua_modules/MatchedPlay_Constants.lua#L55

When playing with the Triumph of Saint Katherine (18 wounds), the decrement wounds function fails because there are only 16 valid wound colors. When decrementing with the hotkey, the error "Indexing a NiL value" comes up. 

This can be resolved by adding 2 more entries to the WOUND_COLOR_CUTOFFS dictionary. 
`local WOUND_COLOR_CUTOFFS = {
    {g=0}, -- 1
    {g=1}, -- 2
    {g=2, o=1}, -- 3
    {g=2, o=1}, -- 4
    {g=3, o=1}, -- 5
    {g=4, o=2}, -- 6
    {g=5, o=2}, -- 7
    {g=6, o=3}, -- 8
    {g=6, o=3}, -- 9
    {g=7, o=4}, -- 10
    {g=7, o=4}, -- 11
    {g=8, o=4}, -- 12
    {g=8, o=4}, -- 13
    {g=8, o=5}, -- 14
    {g=9, o=5}, -- 15
    {g=9, o=5}, -- 16
    {g=9, o=5}, -- 17
    {g=9, o=5} -- 18
}`

Additionally, a more robust way of dealing with more wounds than 18 may need to be thought of, but the proposed solution should work for all models up to 18 wounds.

**Comment by ThePants999** [comment]
Damn, I thought I'd done this already, I had Triumph complaints weeks ago - guess I'm hallucinating :D  Thanks.

**Comment by appoteres** [comment]
Happy to help!

**Comment by ThePants999** [comment]
But I've checked in 2376bcd1e38afa98dd9b259a46153b2017bd9eac anyway as a workaround.
